<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Lakcím',
    'Are you sure? Every data belongs this user will be deleted!' => 'Biztos vagy benne? A felhasználóhoz tartozó összes adat törlődni fog!',
    'Basic info' => 'Alapadatok',
    'Birth date' => 'Születési dátum',
    'Cancel' => 'Mégse',
    'Contact info' => 'Kapcsolat',
    'Create failed' => 'Sikertelen létrehozás',
    'Create successful' => 'Sikeres létrehozás',
    'Created at' => 'Létrehozva',
    'Created by' => 'Létrehozta',
    'Delete' => 'Törlés',
    'Delete failed' => 'A törlés nem sikerült',
    'Delete successful' => 'Sikeres törlés',
    'Driving license' => 'Jogosítvány',
    'Email address' => 'Email cím',
    'Email address not found' => 'Az email cím nem található',
    'Fill your email address below to reset password' => 'Add meg az email címedet',
    'Forgotten password' => 'Elfelejtett jelszó',
    'Format: +36301234567' => 'Formátum: +36301234567',
    'Full name' => 'Teljes név',
    'Generate' => 'Generálás',
    'Invalid email / password' => 'Hibás email cím / jelszó',
    'Invalid token!' => 'Hibás token!',
    'Join date' => 'Csatlakozás ideje',
    'Last activity' => 'Utolsó aktivitás',
    'Login' => 'Bejelentkezés',
    'Login data' => 'Bejelentkezési adatok',
    'New password' => 'Új jelszó',
    'New password (repeat)' => 'Új jelszó (újra)',
    'New password is saved!' => 'Az új jelszó elmentve!',
    'New volunteer' => 'Új önkéntes',
    'Nickname' => 'Becenév',
    'No' => 'Nincs',
    'Password' => 'Jelszó',
    'Password (repeat)' => 'Jelszó (újra)',
    'Password reset request' => 'Jelszó helyreállítása',
    'Phone number' => 'Telefonszám',
    'Please login' => 'Jelentkezz be',
    'Profile image' => 'Profilkép',
    'Remember me' => 'Emlékezz rám',
    'Reset password' => 'Új jelszó beállítása',
    'Role' => 'Szerepkör',
    'Save' => 'Mentés',
    'Search by email, name, and others' => 'Keress email cím, név, vagy egyéb adatok alapján',
    'Send email after create' => 'Email küldése felvétel után',
    'Set a new password below' => 'Add meg az új jelszavadat',
    'Settings' => 'Beállítások',
    'Two passwords must be the same' => 'A két jelszónak egyeznie kell',
    'Update' => 'Módosítás',
    'Update failed' => 'A mentés nem sikerült',
    'Update successful' => 'Sikeres mentés',
    'Update volunteer: {name}' => 'Önkéntes adatainak módosítása: {name}',
    'Updated at' => 'Utoljára módosítva',
    'Updated by' => 'Utoljára módosította',
    'Volunteers' => 'Önkéntesek',
    'We sent you an email, please follow the instructions in it' => 'Levelet küldtünk az email címedre, kérjük, kövesd az ott leírtakat',
    'Welcome!' => 'Üdvözlünk!',
    'Yes' => 'Van',
    'and' => 'és',
    'day' => 'napja',
    'days' => 'napja',
    'inactive' => 'inaktív',
    'month' => 'hónapja',
    'months' => 'hónapja',
    'year' => 'éve',
    'years' => 'éve',
    'Facebook' => '',
    'Missing token!' => 'Hiányzó token!',
    'Skype' => '',
    'Groups' => 'Csoportok',
    'All groups' => 'Minden csoport',
    'Other' => 'Egyéb',
    'There are no groups' => 'Még nem csatlakozott csoprothoz',
    'Events' => 'Események',
];
